### ISSUE TITLE
Cant run into docker interactive tty

### ISSUE THREAD

**Issue by regisxu** [Maximus5/cygwin-connector#26]
Run `docker run -it alpine sh` show error message:

the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

it works well without cygwin-connector

**Comment by Maximus5** [comment]
Why do you post here the Docker issue?

**Comment by regisxu** [comment]
I run this command ins ConEmu,  following this the task commands, which use conemu-msys2:

```
set CHERE_INVOKING=1 & set "PATH=%ConEmuDir%\..\msys64\usr\bin;%PATH%" & %ConEmuBaseDirShort%\conemu-msys2-64.exe -new_console:p:h0 %ConEmuDir%\..\msys64\usr\bin\bash.exe --login -i -new_console:C:"%ConEmuDir%\..\msys64\msys2.ico"
```
And if I start task without conemu-msys2 docker command works, so I think maybe there is something in conemu-msys2.

**Comment by Maximus5** [comment]
The Docker explicitly states that 

    the input device is not a TTY. If you are using mintty, try prefixing the command with 'winpty'

It is not absolutely correct message, but you may understand that you can't run Docker in mintty (which is POSIX TTY). Connector is POSIX TTY too.
Conclusion: don't run Docker from connector because it requires conhost API.

So, this is not a ConEmu or connector issue.
